export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_USER = "GET_USER";
export const GET_USER_PROFILE = "GET_USER_PROFILE"
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
